# Generated by Django 5.2.1 on 2025-06-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('consultaid', models.AutoField(primary_key=True, serialize=False)),
                ('fechaconsulta', models.DateTimeField()),
                ('motivocita', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consultas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultaservicios',
            fields=[
                ('consultaservicioid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fechaservicio', models.DateTimeField()),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consultaservicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuotasplanpago',
            fields=[
                ('cuotaid', models.AutoField(primary_key=True, serialize=False)),
                ('numerocuota', models.IntegerField()),
                ('montocuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechavencimiento', models.DateField()),
                ('fechapago', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuotasplanpago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('especialidadid', models.AutoField(primary_key=True, serialize=False)),
                ('nombreespecialidad', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especialidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('facturaid', models.AutoField(primary_key=True, serialize=False)),
                ('numerofactura', models.CharField(max_length=20)),
                ('fechaemision', models.DateTimeField()),
                ('fechavencimiento', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('impuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fichaclinico',
            fields=[
                ('fichaid', models.AutoField(primary_key=True, serialize=False)),
                ('fechaapertura', models.DateTimeField(blank=True, null=True)),
                ('motivoconsulta', models.TextField(blank=True, null=True)),
                ('diagnosticoinicial', models.TextField(blank=True, null=True)),
                ('antecedentespersonales', models.TextField(blank=True, null=True)),
                ('antecedentesfamiliares', models.TextField(blank=True, null=True)),
                ('signosvitales', models.JSONField(blank=True, null=True)),
                ('tratamientosugerido', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'fichaclinico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('habitacionid', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('disponible', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'habitaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospitalizaciones',
            fields=[
                ('hospitalizacionid', models.AutoField(primary_key=True, serialize=False)),
                ('fechaingreso', models.DateTimeField()),
                ('fechaalta', models.DateTimeField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamientoaplicado', models.TextField(blank=True, null=True)),
                ('motivohospitalizacion', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hospitalizaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospitalizacionservicios',
            fields=[
                ('hospitalizacionservicioid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fechaservicio', models.DateTimeField()),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hospitalizacionservicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metodospago',
            fields=[
                ('metodopagoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('requiereverificacion', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metodospago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PacienteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'paciente_audit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('pacienteid', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numerodocumento', models.CharField(max_length=20)),
                ('tipodocumento', models.CharField(blank=True, max_length=20, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('gruposanguineo', models.CharField(blank=True, max_length=5, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pagoid', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechapago', models.DateTimeField()),
                ('numeroreferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('personalid', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numerodocumento', models.CharField(max_length=20, unique=True)),
                ('tipodocumento', models.CharField(blank=True, max_length=20, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaingreso', models.DateField()),
                ('rol', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planespago',
            fields=[
                ('planpagoid', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('numerocuotas', models.IntegerField()),
                ('montototal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'planespago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('servicioid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costopacienteasegurado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requiereprescripcion', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposalta',
            fields=[
                ('tipoaltaid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tiposalta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposhabitacion',
            fields=[
                ('tipohabitacionid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('costodiario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tiposhabitacion',
                'managed': False,
            },
        ),
    ]
