# Generated by Django 5.2.1 on 2025-06-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuellaDactilar',
            fields=[
                ('huellaid', models.AutoField(primary_key=True, serialize=False)),
                ('pacienteid', models.IntegerField()),
                ('mano', models.CharField(max_length=10)),
                ('dedo', models.CharField(max_length=20)),
                ('template', models.BinaryField()),
                ('fecharegistro', models.DateTimeField()),
            ],
            options={
                'db_table': 'huellasdactilares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DispositivoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=40, unique=True)),
                ('rol_autorizado', models.CharField(choices=[('Administrador', 'Administrador'), ('Doctor', 'Doctor'), ('Enfermeria', 'Enfermeria'), ('Caja', 'Caja')], max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispositivo Token',
                'verbose_name_plural': 'Dispositivos Tokens',
                'db_table': 'dispositivo_token',
            },
        ),
        migrations.AlterModelOptions(
            name='pacienteaudit',
            options={},
        ),
    ]
