# Generated by Django 5.2.1 on 2025-06-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_huelladactilar_dispositivotoken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacienteaudit',
            options={'managed': False},
        ),
    ]
