from django.urls import path
from . import views_admin
from .views_admin import (
    dashboard_view, registrar_personal, listar_personal, editar_personal,
    inactivar_personal, reactivar_personal,
    listar_pacientes, ver_paciente,
    editar_paciente, inactivar_paciente, reactivar_paciente,
    exportar_pacientes, listar_especialidades, registrar_especialidad,
    editar_especialidad, eliminar_especialidad,
    listar_servicios, registrar_servicio, editar_servicio,
    eliminar_servicio, historial_paciente, listar_facturas,
    listar_pagos, listar_consultas, detalle_consulta, reportes_estadisticas,
    control_accesos, configuraciones_generales, descargar_backup,
    listar_habitaciones, registrar_habitacion, editar_habitacion, eliminar_habitacion,
    listar_tipos_habitacion, registrar_tipohabitacion, editar_tipohabitacion, eliminar_tipohabitacion,
    listar_metodos_pago, registrar_metodo_pago, editar_metodo_pago, eliminar_metodo_pago,
    inicio_admin
)


urlpatterns = [
    path('', dashboard_view, name='admin_dashboard'),
    path('inicio/', inicio_admin, name='inicio_admin'),
    path('registrar_personal/', registrar_personal, name='registrar_personal'),
    path('listar_personal/', listar_personal, name='listar_personal'),
    path('personal/<int:personal_id>/editar/', editar_personal, name='editar_personal'),
    path('personal/<int:personal_id>/inactivar/', inactivar_personal, name='inactivar_personal'),
    path('personal/<int:personal_id>/reactivar/', reactivar_personal, name='reactivar_personal'),
    path('listar_pacientes/', listar_pacientes, name='listar_pacientes'),
    path('paciente/<int:paciente_id>/', ver_paciente, name='ver_paciente_admin'),
    path('paciente/<int:paciente_id>/editar/', editar_paciente, name='editar_paciente'),
    path('paciente/<int:paciente_id>/inactivar/', inactivar_paciente, name='inactivar_paciente'),
    path('paciente/<int:paciente_id>/reactivar/', reactivar_paciente, name='reactivar_paciente'),
    path('exportar_pacientes/', exportar_pacientes, name='exportar_pacientes'),
    path('especialidades/', listar_especialidades, name='listar_especialidades'),
    path('especialidades/nueva/', registrar_especialidad, name='registrar_especialidad'),
    path('especialidades/<int:especialidad_id>/editar/', editar_especialidad, name='editar_especialidad'),
    path('especialidades/<int:especialidad_id>/eliminar/', eliminar_especialidad, name='eliminar_especialidad'),
    path('servicios/', listar_servicios, name='listar_servicios'),
    path('servicios/nuevo/', registrar_servicio, name='registrar_servicio'),
    path('servicios/<int:servicio_id>/editar/', editar_servicio, name='editar_servicio'),
    path('servicios/<int:servicio_id>/eliminar/', eliminar_servicio, name='eliminar_servicio'),
    path('paciente/<int:paciente_id>/historial/', historial_paciente, name='historial_paciente_admin'),
    path('facturas/', listar_facturas, name='listar_facturas'),
    path('pagos/', listar_pagos, name='listar_pagos'),
    path('habitaciones/', listar_habitaciones, name='listar_habitaciones'),
    path('habitaciones/nueva/', registrar_habitacion, name='registrar_habitacion'),
    path('habitaciones/<int:habitacion_id>/editar/', editar_habitacion, name='editar_habitacion'),
    path('habitaciones/<int:habitacion_id>/eliminar/', eliminar_habitacion, name='eliminar_habitacion'),
    path('tipos_habitacion/', listar_tipos_habitacion, name='listar_tipos_habitacion'),
    path('tipos_habitacion/nueva/', registrar_tipohabitacion, name='registrar_tipohabitacion'),
    path('tipos_habitacion/<int:tipo_id>/editar/', editar_tipohabitacion, name='editar_tipohabitacion'),
    path('tipos_habitacion/<int:tipo_id>/eliminar/', eliminar_tipohabitacion, name='eliminar_tipohabitacion'),
    path('metodos_pago/', listar_metodos_pago, name='listar_metodos_pago'),
    path('metodos_pago/nuevo/', registrar_metodo_pago, name='registrar_metodo_pago'),
    path('metodos_pago/<int:metodo_id>/editar/', editar_metodo_pago, name='editar_metodo_pago'),
    path('metodos_pago/<int:metodo_id>/eliminar/', eliminar_metodo_pago, name='eliminar_metodo_pago'),
    path('consultas/', listar_consultas, name='listar_consultas'),
    path('consultas/<int:consulta_id>/', detalle_consulta, name='detalle_consulta'),
    path('reportes/', reportes_estadisticas, name='reportes_estadisticas'),
    path('accesos/', control_accesos, name='control_accesos'),
    path('configuraciones/', configuraciones_generales, name='configuraciones_generales'),
    path('backup/', descargar_backup, name='descargar_backup'),
    # path('api/registrar-huella/', views_admin.registrar_huella, name='registrar_huella_api'),   
    # path('api/biometrico/resultado/', views_admin.resultado_biometrico, name='resultado_biometrico'),
]
